export const lang = {
  btnCancel: "Hủy",
  btnSubmit: "Xác nhận",
  videoTutorial: {
    list: {
      tittle: "Danh sách Video Tutorials",
    },
    add: {
      tittle: "Danh sách Video Tutorials",
      name: "Tên video",
      description: "Chi tiết",
      order: "Sắp xếp",
      link: "link",
      servicePackage: "Gói",
      type: "Thể loại",
    },
  },
  videoTutorialType: {
    list: {
      tittle: "Thể loại Video Tutorials",
    },
    add: {
      tittle: "Thể loại Video Tutorials",
      name: "Tên video",
      description: "Mô tả",
    },
  },
  customerManagement: {
    view: {
      tittle: "Customer Management",
      subTittle:
        "Quản lý toàn bộ khách hàng Aiva (Free, Paid, Expired...), sử dụng bộ lọc nâng cao, thao tác hàng loạt, và xem chi tiết hồ sơ. Tích hợp cột “Last Contact”, “Owner”, “Churn Status”...",
      filterLabel: "Saved Filter / Segment:",
      loadSegment: "Load Segment",
      saveCurrentFilter: "Save Current Filter",
      filterCustomer: "Bộ Lọc Khách Hàng",
      servicePackage: "Gói dịch vụ",
      accountStatus: "Tình trạng tài khoản",
      surveyTag: "Thẻ khảo sát",
      creditUser: "Credit Used (%)",
      churnStatus: "Trạng thái Churn",
      lastLogin: "Ngày đăng nhập cuối",
      ownerSales: "Owners (Sales)",
      keyword: "Từ khóa",
      csvExport: "Xuất CSV",
      dataEnter: "Nhập dữ liệu",
      apiIntergration: "Tích hợp API",
      sendEmails: "Gửi Email Hàng Loạt",
      assignOwners: "Phân lead cho sale",
      markasChurn: "Mark as Churn",
      customerList: "Danh Sách Khách Hàng",
      subContent:
        "Tích chọn user, thực hiện mass actions, hoặc xem chi tiết (popup).",
    },
  },
  dealDetail: {
    view: {
      tittle: "Deal Detail",
      subTittle:
        "Thông tin chi tiết deal: gói, khách hàng, usage, survey, tasks & notes...",
      subTaskRelative: "Nhiệm vụ để chốt deal: call, email, demo...",
      taskRelative: "Tasks Liên Quan",
      dealInfo: "Thông tin Deal",
      dealName: "Tên Deal",
      stage: "Stage hiện tại",
      estimatePrice: "Giá Dự Kiến",
      dealDeadline: "Deadline Chốt",
      customer: "Khách Hàng",
      emailName: "Tên/Email",
      creditUsed: "Credit Used",
      surveyTag: "Survey Tag",
      lastLogin: "Last Login",
      owner: "Owner (Sale)",
      notes: "Notes",
      subNotes: "Lịch sử trao đổi, ghi chú về deal.",
      updateStage: "Cập nhật Stage",
    },
  },
  surveyCustomer: {
    view: {
      header: "Freemium & Survey Dashboard",
      subheader:
        "Theo dõi toàn diện: Free/Paid users, dữ liệu khảo sát, credit usage, cơ hội upsell, hoa hồng đào tạo, và onboarding funnel.",
      AIPurpose: "Mục đích AI (Từ Survey)",
      creditUsageDistribution: "Phân phối Credit Usage (Free)",
      needAttention: "Need Attention (Cơ hội Upsell / Churn Risk)",
      customer: "Khách Hàng",
      email: "Email",
      dayIdle: "Days Idle",
      creditUser: "Credit Used",
      topCommission: "Top CTV & Hoa hồng đào tạo (5%)",
      ctv: "CTV",
      numberRefferrals: "Số KH Giới Thiệu",
      revenueGenerated: "Doanh Thu Tạo",
      commission: "Hoa hồng (5%)",
      onboardingFunnel: "Onboarding Funnel",
      numberByStep: "(Bar/Line chart hiển thị số user qua từng bước)",
    },
  },
  salesDashBoard: {
    view: {
      header: "Sales Dashboard",
      subheader:
        "Tổng quan KPI bán hàng, quản lý deal, tasks, notes ngay tại chỗ.",
      dealbystage: "Phân Bổ Deals Theo Stage",
      revenueTargetMonth: "Doanh Thu / Mục Tiêu (Tháng)",
      salemanageTask:
        "Quản lý nhiệm vụ bán hàng, follow-up deal, call/email...",
      needAttention: "Tasks Cần Xử Lý",
      customer: "Khách Hàng",
      email: "Email",
      dayIdle: "Days Idle",
      creditUser: "Credit Used",
      topCommission: "Top CTV & Hoa hồng đào tạo (5%)",
      ctv: "CTV",
      numberRefferrals: "Số KH Giới Thiệu",
      revenueGenerated: "Doanh Thu Tạo",
      commission: "Hoa hồng (5%)",
      onboardingFunnel: "Onboarding Funnel",
      numberByStep: "(Bar/Line chart hiển thị số user qua từng bước)",
      addTask: "Tạo Task",
      addNote: "Thêm Note",
      tittle: "Tiêu đề",
      deal: "Deal (nếu có)",
      deadline: "Deadline",
      status: "Trạng thái",
      action: "Hành động",
      detail: "Chi tiết",
      salesNote: "Ghi Chú Bán Hàng",
      salesHistory:
        "Lịch sử liên hệ, trao đổi, feedback từ KH liên quan đến bán hàng.",
      date: "Ngày",
      description: "Nội dung",
    },
  },
  needAttention: {
    view: {
      header: "Need Attention / Cơ hội Upsell / Churn Risk",
      subheader:
        "Tập trung mọi khách hàng “có dấu hiệu” cần chăm sóc đặc biệt: cạn credit, idle, sắp hết hạn, feedback kém, v.v. Giúp tối ưu chuyển đổi và ngăn chặn churn.",
      dealbystage: "Phân Bổ Deals Theo Stage",
      revenueTargetMonth: "Doanh Thu / Mục Tiêu (Tháng)",
      salemanageTask:
        "Quản lý nhiệm vụ bán hàng, follow-up deal, call/email...",
      needAttention: "Bộ Lọc Nâng Cao",
      customer: "Khách Hàng",
      email: "Email",
      dayIdle: "Days Idle",
      creditUser: "Credit Used",
      topCommission: "Top CTV & Hoa hồng đào tạo (5%)",
      ctv: "CTV",
      numberRefferrals: "Số KH Giới Thiệu",
      revenueGenerated: "Doanh Thu Tạo",
      commission: "Hoa hồng (5%)",
      onboardingFunnel: "Onboarding Funnel",
      numberByStep: "(Bar/Line chart hiển thị số user qua từng bước)",
      addTask: "Tạo Task",
      addNote: "Thêm Note",
      tittle: "Tiêu đề",
      deal: "Deal (nếu có)",
      deadline: "Deadline",
      status: "Trạng thái",
      action: "Hành động",
      detail: "Chi tiết",
      salesNote: "Ghi Chú Bán Hàng",
      salesHistory:
        "Lịch sử liên hệ, trao đổi, feedback từ KH liên quan đến bán hàng.",
      date: "Ngày",
      description: "Nội dung",
      infoUserCredit:
        "Những user free / paid đang sắp hết credit. Cơ hội upsell mua thêm credit hoặc nâng gói.",
      userCredit: "User Cạn Credit (<10%)",
      userIdle: "User Idle (>14 ngày)",
      userNotLogin:
        "Danh sách user đã lâu không đăng nhập, dễ rơi vào churn nếu không chăm sóc.",
      expriredPackage: "KH Sắp Hết Hạn Gói (7-14-30d)",
      upsellExtend:
        "Những user trả phí sẽ hết hạn sớm. Cần upsell gia hạn / upgrade.",
      negativeFeedback: "KH Feedback kém / Negative",
      subNegativeFeedback:
        "Danh sách user đánh giá thấp (1-2 sao) hoặc feedback “không hài lòng,” cần CSKH giải quyết gấp.",
      surveyTagCustomer: "KH Sẵn sàng chi cao (Survey Tag)",
      subSurveyTagCustomer:
        "Danh sách user có “high-budget” trong survey, dễ upsell gói VIP, plugin AI nâng cao.",
    },
  },
  customerDetail: {
    view: {
      header: "Customer Detail",
      subheader:
        "Thông tin chi tiết về khách hàng, hành vi sử dụng, lịch sử giao dịch & kế hoạch chăm sóc.",
      customerInfo: "Thông Tin Khách Hàng",
      name: "Tên",
      email: "Email",
      phoneNumber: "Số điện thoại",
      job: "Ngành nghề",
      role: "Vai trò",
      owner: "Owner (Sale)",
      behavior: "Hành Vi & Insights",
      AIExperienceLevel: "Mức độ kinh nghiệm AI",
      potentialBudget: "Ngân sách tiềm năng",
      AIUsageGoal: "Mục tiêu sử dụng AI",
      firstFeature: "Tính năng quan tâm đầu tiên",
      leadScore: "Lead Score",
      call: "GỌI NGAY",
      sendEmail: "GỬI EMAIL",
      appointment: "ĐẶT LỊCH HẸN",
      usageBehavior: "Hành Vi Sử Dụng",
      lastLogin: "Lần đăng nhập gần nhất",
      loginFrequency: "Tần suất đăng nhập",
      numberAgentUsers: "Số lượng sử dụng Agents",
      topMostUsedAI: "Top trợ lý AI dùng nhiều nhất",
      financialStatus: "Tình Trạng Tài Chính & Giao Dịch",
      currentPackage: "Gói hiện tại",
      dayActive: "Ngày kích hoạt",
      dateExpired: "Ngày hết hạn",
      numberUpdatePackage: "Số lần nâng cấp gói",
      lastByCredit: "Lần mua credit gần nhất",
      creditRate: "Tỷ lệ sử dụng credit",
      totalAmoutSpend: "Tổng số tiền đã chi tiêu",
      careFollowPlan: "Chăm Sóc & Kế Hoạch Tiếp Theo",
      suggestAction: "Gợi ý hành động tiếp theo",
      operationFrequency: "Tần suất đăng nhập",
      usageFrequency: "Tần suất sử dụng",
      engagementScore: "Điểm tương tác",
      operationFrequencyStatus: "Tần suất hoạt động",
    },
  },
  orderList: {
    view: {
      tittle: "Danh sách đơn hàng",
      subTittle:
        "Quản lý toàn bộ khách hàng Aiva (Free, Paid, Expired...), sử dụng bộ lọc nâng cao, thao tác hàng loạt, và xem chi tiết hồ sơ. Tích hợp cột “Last Contact”, “Owner”, “Churn Status”...",
      filterLabel: "Saved Filter / Segment:",
      loadSegment: "Load Segment",
      saveCurrentFilter: "Save Current Filter",
      filterCustomer: "Bộ Lọc Khách Hàng",
      servicePackage: "Gói dịch vụ",
      accountStatus: "Tình trạng tài khoản",
      surveyTag: "Thẻ khảo sát",
      creditUser: "Credit Used (%)",
      churnStatus: "Trạng thái Churn",
      lastLogin: "Ngày đăng nhập cuối",
      ownerSales: "Owners (Sales)",
      keyword: "SĐT/Mã KH",
      csvExport: "Xuất CSV",
      bulkbrosing: "Duyệt hàng loạt",
      uploadList: "Tải lên danh sách",
      sendEmails: "Gửi Email Hàng Loạt",
      assignOwners: "Phân lead cho sale",
      markasChurn: "Mark as Churn",
      customerList: "Danh Sách Khách Hàng",
      subContent:
        "Tích chọn user, thực hiện mass actions, hoặc xem chi tiết (popup).",
      addOrder: "Tạo đơn hàng",
    },
  },
  listTicket: {
    view: {
      header: "Danh sách Ticket",
      subTittle:
        "Quản lý toàn bộ khách hàng Aiva (Free, Paid, Expired...), sử dụng bộ lọc nâng cao, thao tác hàng loạt, và xem chi tiết hồ sơ. Tích hợp cột “Last Contact”, “Owner”, “Churn Status”...",
      filterLabel: "Saved Filter / Segment:",
      loadSegment: "Load Segment",
      saveCurrentFilter: "Save Current Filter",
      filterCustomer: "Bộ Lọc Khách Hàng",
      servicePackage: "Gói dịch vụ",
      accountStatus: "Tình trạng tài khoản",
      surveyTag: "Thẻ khảo sát",
      creditUser: "Credit Used (%)",
      churnStatus: "Trạng thái Churn",
      lastLogin: "Ngày đăng nhập cuối",
      ownerSales: "Owners (Sales)",
      keyword: "Từ khóa",
      csvExport: "Xuất CSV",
      bulkbrosing: "Chuyển Agent",
      uploadList: "Đóng Ticket",
      sendEmails: "Gửi Email Hàng Loạt",
      assignOwners: "Phân lead cho sale",
      markasChurn: "Mark as Churn",
      customerList: "Danh Sách Khách Hàng",
      subContent:
        "Tích chọn user, thực hiện mass actions, hoặc xem chi tiết (popup).",
      addOrder: "Tạo đơn hàng",
      allaction: "Thao tác hàng loạt",
    },
  },
  afterSale: {
    view: {
      header: "Quản Lý Khách Hàng Sau Bán",
      subTittle:
        "Quản lý toàn bộ khách hàng Aiva (Free, Paid, Expired...), sử dụng bộ lọc nâng cao, thao tác hàng loạt, và xem chi tiết hồ sơ. Tích hợp cột “Last Contact”, “Owner”, “Churn Status”...",
      filterLabel: "Saved Filter / Segment:",
      loadSegment: "Load Segment",
      saveCurrentFilter: "Save Current Filter",
      filterCustomer: "Bộ Lọc Khách Hàng",
      servicePackage: "Gói dịch vụ",
      accountStatus: "Tình trạng tài khoản",
      surveyTag: "Thẻ khảo sát",
      creditUser: "Credit Used (%)",
      churnStatus: "Trạng thái Churn",
      lastLogin: "Ngày đăng nhập cuối",
      ownerSales: "Owners (Sales)",
      keyword: "Từ khóa",
      csvExport: "Xuất CSV",
      bulkbrosing: "Gửi Email MKT",
      uploadList: "Upsell",
      chat: "Chat Now",
      onboarding: "Nhắc Onboarding",
      sendEmails: "Gửi Email Hàng Loạt",
      assignOwners: "Phân lead cho sale",
      markasChurn: "Mark as Churn",
      customerList: "Danh Sách Khách Hàng",
      subContent:
        "Tích chọn user, thực hiện mass actions, hoặc xem chi tiết (popup).",
      addOrder: "Tạo đơn hàng",
      allaction: "Thao tác hàng loạt",
    },
  },
  errorDetected: "Lỗi không xác định",
  update: "Cập nhật",
  deal: "Chốt Deal (Won)",
  cancelDeal: "Hủy Deal (Lost)",
};
