import { createStyles, makeStyles } from "@mui/styles";
import { Theme } from "@mui/material";
import { colorVal } from "@/src/constants/colors";
export const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    header: {
      height: "56px",
      padding: "0 12px",
      backgroundColor: "#FFFFFF",
      borderBottom: "1px solid #DDE0E5",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      position: "sticky",
      zIndex: "1000",
      top: "0",
    },
    header_right: {
      display: "flex",
      alignItems: "center",
      gap: "12px",
      position: "relative",
    },
    header_right_item: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
    },
    header_right_item_img: {
      cursor: "pointer",
    },
    header_right_item_noti: {
      position: "relative",
    },
    header_right_item_noti_count: {
      padding: "2px 6px",
      backgroundColor: "#C9372C",
      borderRadius: "8px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: "#FFFFFF",
      fontSize: "12px",
      fontWeight: "400",
      lineHeight: "12px",
      position: "absolute",
      right: "-5px",
      top: "-3px",
    },

    //setting account
    account_setting: {
      position: "absolute",
      top: "40px",
      right: "0",
      width: "246px",
      backgroundColor: "#FFFFFF",
      borderRadius: "8px",
      boxShadow: "0px 8px 12px rgba(9, 30, 66, 0.31)",
      zIndex: "3",
      padding: "6px",
      display: "flex",
      flexDirection: "column",
      gap: "8px",
    },
    account_setting_info: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      gap: "8px",
    },
    account_setting_info_item1: {
      display: "flex",
      justifyContent: "flex-start",
      gap: "8px",
      alignItems: "center",
    },
    account_setting_info_item: {
      display: "flex",
      justifyContent: "flex-start",
      gap: "8px",
      alignItems: "center",
      cursor: "pointer",
      "&:hover": {
        backgroundColor: "#F4F5F7",
      },
    },
    account_setting_info_item_name: {
      fontSize: "14px",
      lineHeight: "20px",
      color: colorVal.dark,
    },
    line: {
      borderBottom: "1px solid #DDE0E5",
    },
    account_setting_logout_name: {
      fontSize: "14px",
      lineHeight: "20px",
      color: "#AE2E24",
    },
    account_setting_img: {
      width: "24px",
      height: "24px",
    },
    account_setting_img_border: {
      width: "30px",
      height: "30px",
      borderRadius: "50%",
      objectFit: "cover",
    },
    dialog: {
      height: "auto",
      backgroundColor: "#FFFFFF",
      borderRadius: "12px",
      border: "1px solid #DDE0E5",
      boxShadow: "0px 8px 12px rgba(9, 30, 66, 0.05)",
      padding: "24px",
      display: "flex",
      flexDirection: "column",
      gap: "24px",
      width: "350px",
      "@media (max-width: 1600px)": {
        gap: "18px",
      },
    },
    dialog_header: {
      position: "sticky",
      width: "100%",
      display: "flex",
      justifyContent: "space-between",
    },
    dialog_title: {
      fontSize: "20px",
      lineHeight: "24px",
      color: colorVal.dark,
      fontWeight: "500",
    },
    content: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      gap: "24px",
      "@media (max-width: 1600px)": {
        gap: "18px",
      },
    },
    dialog_content: {
      width: "100%",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "24px",
      "@media (max-width: 1600px)": {
        gap: "18px",
      },
    },
    dialog_content_item: {
      width: "100%",
      display: "flex",
      gap: "16px",
      justifyContent: "space-between",
      alignItems: "center",
    },
    dialog_content_item_info: {
      display: "flex",
      flexDirection: "column",
      gap: "6px",
      flexGrow: 1,
    },
    dialog_content_item_info_name: {
      fontSize: "14px",
      lineHeight: "21.7px",
      color: colorVal.dark,
      fontWeight: "500",
    },
    input: {
      backgroundColor: "#fff",
      borderRadius: "8px",
      height: "48px",
      border: "1px solid #DFE1E7",
      "& .MuiOutlinedInput-root": {
        padding: "10px 8px",
        "& input": {
          padding: 0,
        },
        "& fieldset": {
          border: "unset",
        },
        "&.Mui-focused fieldset": {
          border: "none",
        },
      },
      "& .MuiFormHelperText-root": {
        marginTop: "-4px",
      },
      "&:focus-within": {
        border: "1px solid #FD9D68 !important",
      },
    },
    dialog_content_item_upload: {
      width: "100px",
      height: "100px",
      borderRadius: "100px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
      backgroundColor: "#F7F8F9",
    },
    dialog_content_item_upload_background: {
      width: "100%",
      height: "80px",
      borderRadius: "4px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
      backgroundColor: "#F7F8F9",
    },
    btn_delete_account: {
      width: "100%",
      height: "48px",
      fontSize: "16px",
      fontWeight: "500",
      lineHeight: "24.8px",
      color: "#AE2E24",
      backgroundColor: "#FFEFE6",
      textTransform: "none",
      borderRadius: "100px",
      "&:hover": {
        backgroundColor: "#f5ded1",
      },
    },
    btn_cancel: {
      width: "100%",
      height: "48px",
      fontSize: "16px",
      fontWeight: "500",
      lineHeight: "24.8px",
      color: "#2E68B1",
      backgroundColor: "#E3ECF8",
      textTransform: "none",
      borderRadius: "100px",
      "&:hover": {
        backgroundColor: "#c0d4ef",
      },
    },
    btn_save: {
      width: "100%",
      height: "48px",
      fontSize: "16px",
      fontWeight: "500",
      lineHeight: "24.8px",
      color: "#FFFFFF",
      backgroundColor: "#2E68B1",
      textTransform: "none",
      borderRadius: "100px",
      "&:hover": {
        backgroundColor: "#1d5091",
      },
    },
    img_upload: {
      cursor: "pointer",
      width: "100%",
      height: "100%",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
    },
    wanning: {
      fontSize: "16px",
      cursor: "pointer",
    },
  }),
);
