import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { Provider as ReduxProvider } from "react-redux";
import { store } from "@store/store";
import Snackbar from "@/src/components/@extended/Snackbar";
import Head from "next/head";
import { PageLayout } from "@/src/components/PageLayout";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { AuthProvider } from "@/src/contexts/AuthContext";

export default function App({ Component, pageProps }: AppProps) {
  const router = useRouter();

  const shouldRenderPageLayout = !["/", "/login"].includes(router.pathname); // Kiểm tra xem các page không cần nav và header

  return (
    <>
      <AuthProvider>
        <Head>
          <title>Aiva</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/images/AivaLogo.svg" />
        </Head>

        <ReduxProvider store={store}>
          {/* render các component thuộc PageLayout */}
          {shouldRenderPageLayout ? (
            <PageLayout>
              <Component {...pageProps} />
            </PageLayout>
          ) : (
            <Component {...pageProps} />
          )}

          <Snackbar />
        </ReduxProvider>
      </AuthProvider>
    </>
  );
}
